name: 'build-and-deplay-action'
on:
  pull_request:
    branches: ['development']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and build
        run: |
          npm ci
          npm run build:gh-pages
          cp "dist/client-app/index.html" "dist/client-app/404.html"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/client-app
